// <auto-generated />
namespace HotelManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GuestTableforce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GuestTableforce));
        
        string IMigrationMetadata.Id
        {
            get { return "202506211502512_GuestTable-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
